services:
  database:
    container_name: alphalabz-database
    build:
      context: ./pocketbase
      dockerfile: Dockerfile.pb
    ports:
      - "8090:8090"
    volumes:
      - ./database/pb_data:/pb/pb_data
      - ./database/pb_hooks:/pb/pb_hooks
      - ./database/pb_migrations:/pb/pb_migrations
    environment:
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@elimt.com}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-strongpassword123}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/api/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - elimt-network

  backend:
    container_name: alphalabz-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.be
    ports:
      - "8080:8080"
    depends_on:
      pocketbase:
        condition: service_healthy
    environment:
      - POCKETBASE_URL=http://pocketbase:8090
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-strongpassword123}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - elimt-network

  frontend:
    container_name: alphalabz-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.fe
    ports:
      - "80:5173"
    environment:
      - VITE_API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - elimt-network

networks:
  elimt-network:
    driver: bridge

volumes:
  pocketbase_data: