server:
    host: 0.0.0.0
    port: 8080

pocketbase:
    host: 0.0.0.0
    port: 8090

Mailer:
    service: gmail
    host: smtp.gmail.com
    port: 587
    username: XXXXXXXXXXXXXXXXXXXX
    password: your_password
    from_address: XXXXXXXXXXXXXXXXXXXX
    use_tls: true

IsInitialized: false
